[build]
buildCommand = "pnpm install && pnpm run db:generate && turbo build -F server"
watchPatterns = ["apps/server/**", "packages/**"]

[deploy]
startCommand = "cd apps/server && node ./dist/index.mjs"
preDeployCommand = "cd packages/db && pnpx prisma migrate deploy"
