[build]
buildCommand = "bun install && bun run db:generate && turbo build -F server"

[deploy]
startCommand = "cd apps/server && bun ./dist/index.js"
preDeployCommand = "cd packages/db && bunx prisma migrate deploy"
watchPatterns = ["apps/server/**", "packages/**"]
