import {
  Activity,
  Award,
  BarChart,
  Battery,
  Bell,
  Bike,
  Bluetooth,
  Book,
  Bookmark,
  Brain,
  Briefcase,
  Brush,
  Building,
  Calendar,
  Camera,
  Car,
  Cat,
  Clipboard,
  Clock,
  Cloud,
  Code,
  Coffee,
  Compass,
  Cpu,
  CreditCard,
  Database,
  Dice1 as Dice,
  Dog,
  Dumbbell,
  Eye,
  FileText,
  Fingerprint,
  Fish,
  Flag,
  Flower,
  Gamepad,
  Gift,
  Glasses,
  Globe,
  GraduationCap,
  Grid3x3 as Grid,
  Headphones,
  Heart,
  Home,
  Image,
  Key,
  Layers,
  Leaf,
  Lightbulb,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  MessageSquare,
  Mic,
  Monitor,
  Moon,
  Music,
  Newspaper,
  Package,
  Palette,
  PenTool,
  PieChart,
  Pill,
  Plane,
  Printer,
  Puzzle,
  QrCode,
  Radio,
  Rocket,
  Scan,
  Scissors,
  Search,
  Settings,
  Shield,
  Ship,
  ShoppingCart,
  Smartphone,
  Star,
  Stethoscope,
  Store,
  Sun,
  Syringe,
  Target,
  Thermometer,
  Timer,
  TrendingUp,
  Trophy,
  Truck,
  Tv,
  Trees as Tree,
  Umbrella,
  User,
  Users,
  Utensils,
  Video,
  Wallet,
  Wifi,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { cn } from "@/lib/utils";

const ICON_MAP: Record<string, LucideIcon> = {
  activity: Activity,
  award: Award,
  "bar-chart": BarChart,
  battery: Battery,
  bell: Bell,
  bike: Bike,
  bluetooth: Bluetooth,
  book: Book,
  bookmark: Bookmark,
  brain: Brain,
  briefcase: Briefcase,
  brush: Brush,
  building: Building,
  calendar: Calendar,
  camera: Camera,
  car: Car,
  cat: Cat,
  clipboard: Clipboard,
  clock: Clock,
  cloud: Cloud,
  code: Code,
  coffee: Coffee,
  compass: Compass,
  cpu: Cpu,
  "credit-card": CreditCard,
  database: Database,
  dice: Dice,
  dog: Dog,
  dumbbell: Dumbbell,
  eye: Eye,
  "file-text": FileText,
  fingerprint: Fingerprint,
  fish: Fish,
  flag: Flag,
  flower: Flower,
  gamepad: Gamepad,
  gift: Gift,
  glasses: Glasses,
  globe: Globe,
  "graduation-cap": GraduationCap,
  grid: Grid,
  headphones: Headphones,
  heart: Heart,
  home: Home,
  image: Image,
  key: Key,
  layers: Layers,
  leaf: Leaf,
  lightbulb: Lightbulb,
  lock: Lock,
  mail: Mail,
  "map-pin": MapPin,
  megaphone: Megaphone,
  "message-square": MessageSquare,
  mic: Mic,
  monitor: Monitor,
  moon: Moon,
  music: Music,
  newspaper: Newspaper,
  package: Package,
  palette: Palette,
  "pen-tool": PenTool,
  "pie-chart": PieChart,
  pill: Pill,
  plane: Plane,
  printer: Printer,
  puzzle: Puzzle,
  "qr-code": QrCode,
  radio: Radio,
  rocket: Rocket,
  scan: Scan,
  scissors: Scissors,
  search: Search,
  settings: Settings,
  shield: Shield,
  ship: Ship,
  "shopping-cart": ShoppingCart,
  smartphone: Smartphone,
  star: Star,
  stethoscope: Stethoscope,
  store: Store,
  sun: Sun,
  syringe: Syringe,
  target: Target,
  thermometer: Thermometer,
  timer: Timer,
  "trending-up": TrendingUp,
  trophy: Trophy,
  truck: Truck,
  tv: Tv,
  tree: Tree,
  umbrella: Umbrella,
  user: User,
  users: Users,
  utensils: Utensils,
  video: Video,
  wallet: Wallet,
  wifi: Wifi,
  wrench: Wrench,
  zap: Zap,
};

interface ProjectIconProps {
  icon: string | null | undefined;
  className?: string;
}

export function ProjectIcon({ icon, className }: ProjectIconProps) {
  const IconComponent = (icon && ICON_MAP[icon]) || Lightbulb;
  return <IconComponent className={cn("size-4", className)} />;
}
